# NOTE: This is the docker-compose for local development. For the production docker-compose, see README.md
services:
  at-home-remote:
    build: .
    volumes:
      - ./data/docker:/usr/src/app/data
      - ./.env:/usr/src/app/.env
    ports:
      - 3000:3000
    restart: unless-stopped