# NOTE: This is the docker-compose for local development. For the production docker-compose, see README.md
services:
  at-home-remote:
    build: .
    volumes:
      - ./data/docker:/usr/src/app/data
      - ./.env:/usr/src/app/.env
    restart: unless-stopped
  nginx:
    build: ./nginx-proxy
    ports:
      - 3044:80
    env_file:
      - ./env.properties
    environment:
      - PROXY_PASS=http://at-home-remote:3000/
    restart: unless-stopped
